apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mbywcw5vr-python
  janus-idp.io/tekton: mbywcw5vr-python
  backstage.io/kubernetes-id: mbywcw5vr-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mbywcw5vr-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
